# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d56032868be76507b2a31ed4d9618bb0d03cf5a181d1a0de49c0ec48bc35c39499bdd83957e7c4aa35bf3b78b4cdb33355054dffe7ee091f3c9a96cc456b81f

test:
  secret_key_base: 0f48cb672583672847ab4914de780defab769690c626216b0edab7fd0fbec0cc5efc81dab0c49a514794ef802f737677c8e49beb41f786abdeebd5351006643d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
